head_lidar_controller:
    controller:
        package: dynamixel_controllers
        module: joint_torque_controller
        type: JointTorqueController
    joint_name: spin_lidar_spin_joint
    joint_speed: 1.0
    motor:
        id: 6
        init: 0
        min: 0
        max: 4095
stab_laser_roll_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: stab_laser_roll_joint
    joint_speed: 10
    motor:
        id: 7
        init: 512
        min: 0
        max: 1023
stab_laser_pitch_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: stab_laser_pitch_joint
    joint_speed: 10
    motor:
        id: 8
        init: 512
        min: 0
        max: 1023
