pub_rate: 1.0 # Optional, defaults to 1.0
base_path: '' # Optional, defaults to ""
analyzers:
  hardware:
    type: AnalyzerGroup
    path: Hardware
    analyzers:
      computers:
        type: GenericAnalyzer
        path: Computers
        contains: [
          'HD Temp',
          'CPU Usage',
          'CPU Temperature',
          'HD Usage',
          'NFS']
      taurob_base_node:
        type: GenericAnalyzer
        path: Taurob Base Node
        find_and_remove_prefix: taurob_base_node
        num_items: 3
      sensors:
        type: AnalyzerGroup
        path: Sensors
        analyzers:
          lidars:
            type: AnalyzerGroup
            path: LIDAR
            analyzers:
              spin_hokuyo:
                type: GenericAnalyzer
                path: Spinning
                find_and_remove_prefix: spin_laser/head_urg_node
                num_items: 2
          vision:
            type: AnalyzerGroup
            path: Cameras
            analyzers:
              arm_thermal_cam:
                type: GenericAnalyzer
                path: Arm Thermal Camera
                find_and_remove_prefix: arm_thermal_cam
      arm:
        type: GenericAnalyzer
        path: Arm
        find_and_remove_prefix: arm_control
        num_items: 4
      jointcontroller:
        type: GenericAnalyzer
        path: Joint Controller
        find_and_remove_prefix: Joint Controller (
        num_items: 3
      bus:
        type: GenericAnalyzer
        path: Dynamixel Serial Bus
        find_and_remove_prefix: Dynamixel Serial Bus (
        num_items: 2
      motor:
        type: GenericAnalyzer
        path: Robotis Motor
        find_and_remove_prefix: Robotis Dynamixel
        num_items: 3
  software:
    type: AnalyzerGroup
    path: Software
    analyzers:
      odom_filter:
        type: GenericAnalyzer
        path: Odom Filter
        find_and_remove_prefix: odom_filter
        num_items: 2
